version: "3.9"

services:

  mongo:
    image: mongo:7.0
    container_name: provisioning-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: provisioning

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: provisioning-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: provisioning-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  provisioning-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: provisioning-service
    depends_on:
      - mongo
      - kafka
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/provisioning
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
