spring:
  application:
    name: provisioning-service

  data:
    mongodb:
      uri: mongodb://localhost:27017/provisioning

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

marketplace:
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      order-paid: provisioning.order-paid
    consumer:
      group-id: provisioning-service

server:
  port: 8080

logging:
  level:
    root: INFO
    liquibase: DEBUG
    org.springframework.data.mongodb: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info
